name: Snapcraft Action
author: Samuel Meuli
description: GitHub Action for setting up Snapcraft

inputs:
  channel:
    description: The channel to install Snapcraft from
    required: false
    default: stable
  skip_install:
    description: Skip installation (login only)
    required: false
  use_lxd:
    description: Whether to install and configure lxd
    required: false
    # tag: deprecate_use_lxd
    deprecationMessage: automatic on ubuntu-20.04 or later

runs:
  using: node20
  main: ./index.js

branding:
  icon: upload-cloud
  color: green
