name: Snapcraft Action
author: Samuel Meuli
description: GitHub Action for setting up Snapcraft

inputs:
  channel:
    description: The channel to install Snapcraft from
    required: false
    default: stable
  snapcraft_token:
    description: Token for logging into Snapcraft
    required: true
  skip_install:
    description: Skip installation (login only)
    required: false
  use_lxd:
    description: Whether to install and configure lxd
    required: false

runs:
  using: node12
  main: ./index.js

branding:
  icon: upload-cloud
  color: green
